version: "3.9"
services:
  auctorize-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: auctorize-server
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - DATABASE_URI="postgresql://postgres:helloworld@db:5432"
      - RAILS_ENV=development
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=helloworld
      - DATABASE_NAME=auctorize_development
      - DATABASE_HOST=pgdb
      - DATABASE_PORT=5432
    volumes:
      - ./server:/mnt/auctorize-server
    depends_on:
      - pgdb
  auctorize-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: auctorize-client
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./client:/mnt/auctorize-client
  pgdb:
    image: postgres:14.3-alpine
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=helloworld
      - PGDATA=/var/lib/postgresql/data
volumes:
  postgres-data: